### ISSUE TITLE
About factorization 1d.

### ISSUE THREAD

**Issue by wenruiLiA15** [prafull7/compmirrors#1]
Hi!, I want to ask how many times it often takes to generate the results shown in the paper.
I have run factorization 1d about 400 times, but none of the results are even close to the ground truth. 
I wonder if I had missed something, I changed the noise level from 0.01 - 0.1, but it didn't show much difference.

**Comment by prafull7** [comment]
Usually, we got the results with a few tries for the provided examples. How many steps did you train each run for? Are the required versions used for the libraries used in the project? Which GPU are you using (we are aware that for some reason this code is unstable on certain GPUs)?

**Comment by wenruiLiA15** [comment]
I trained over 10000 steps for each run at first, I found that usually after 4000 steps the results will be settled.
GPU i'm using is Nvidia GTX 3090, and the code was run in torch 1.8.0. 
Not all the libraries are the same as required, but the other code about factorize light transport matrix run successfully, I not sure that's the problem

**Comment by prafull7** [comment]
Can you send me the output for the 2D factorization on prafull _at_ mit _dot_ edu?
Can try running it with the required libraries? Might be easier to see if there is a bug.
